smithy-lang/smithy-java

logging/src/main/java/software/amazon/smithy/java/logging/JclLogger.java, logging/src/main/java/software/amazon/smithy/java/logging/JdkSystemLogger.java, logging/src/main/java/software/amazon/smithy/java/logging/Log4j2Logger.java, logging/src/test/java/software/amazon/smithy/java/logging/JclLoggerIsolatedTest.java, logging/src/test/java/software/amazon/smithy/java/logging/JdkSystemLoggerTest.java, logging/src/test/java/software/amazon/smithy/java/logging/Log4j2LoggerIsolatedTest.java, logging/src/test/java/software/amazon/smithy/java/logging/LoggerTestBase.java
Fix parameters mismatch in logging methods and add tests for verifying the same
=> Fix parameters mismatch in logging methods and add tests for verifying the same

settings.gradle.kts
=> Remove non-existent subprojects

codegen/core/src/main/java/software/amazon/smithy/java/codegen/integrations/core/NodeWriter.java
=> Fix call to ArrayNode#builder

buildSrc/src/main/kotlin/smithy-java.java-conventions.gradle.kts, gradle/libs.versions.toml, protocol-test-harness/build.gradle.kts
Required for upgrade to JUnit 5.12 in #598
=> Add explicit dependency on junit-platform-launcher

codecs/json-codec/src/test/java/software/amazon/smithy/java/json/JsonSerializerTest.java, examples/restjson-client/build.gradle.kts
=> Add missing test dependencies for restjson integ

.git-blame-ignore-revs
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
#541 was included
=> Add formatting changes to ignore-blame

codegen/core/src/main/java/software/amazon/smithy/java/codegen/JavaSymbolProvider.java, codegen/core/src/main/resources/software/amazon/smithy/java/codegen/reserved-words.txt, codegen/core/src/test/java/software/amazon/smithy/java/codegen/NamingTest.java, codegen/core/src/test/resources/software/amazon/smithy/java/codegen/naming-test.smithy
=> Fix naming of member names which are ALL CAPS. Also escape java literals

dynamic-schemas/build.gradle.kts, dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/SchemaInterceptingSerializer.java, dynamic-schemas/src/test/java/software/amazon/smithy/java/dynamicschemas/SchemaGuidedDocumentBuilderTest.java
=> Fix nested dynamic wrapped structures and unions

protocol-test-harness/build.gradle.kts
=> Remove unused dep

examples/end-to-end/src/it/java/software/amazon/smithy/java/server/example/RoundTripTests.java, examples/end-to-end/src/main/java/software/amazon/smithy/java/server/example/Order.java, examples/end-to-end/src/main/java/software/amazon/smithy/java/server/example/OrderTracker.java
See https://github.com/smithy-lang/smithy-java/actions/runs/14368980985/job/40288206436?pr=641#step:6:605
=> Fix flaky test in examples

settings.gradle.kts
This got lost in the module refactoring in the previous PR
=> Add aws-service-bundle module

context/src/main/java/software/amazon/smithy/java/context/ArrayStorageContext.java, context/src/main/java/software/amazon/smithy/java/context/Context.java, context/src/main/java/software/amazon/smithy/java/context/MapStorageContext.java, context/src/main/java/software/amazon/smithy/java/context/UnmodifiableContext.java
So you can write `context().put(...).put(...);`
=> Make Context::put calls chainable

codecs/json-codec/src/main/java/software/amazon/smithy/java/json/JsonCodec.java, codecs/json-codec/src/main/java/software/amazon/smithy/java/json/JsonSettings.java, codecs/json-codec/src/main/java/software/amazon/smithy/java/json/jackson/JacksonJsonSerializer.java
This wasn't being plumbed all the way through
=> Fix integration for JsonSettings::serializeTypeInDocuments

cli/src/main/java/software/amazon/smithy/java/cli/SmithyCall.java
The CLI now performs a cascade of checks for its SigV4 signing name in the following order:
1. First it checks if the shape has a `SigV4Trait` and uses its name if present
2. If not, it checks if the shape has a `ServiceTrait` and uses its ARN namespace if present
3. If neither trait is present, it defaults to the namespace of the shape ID
=> Improve smithy-call's handling of SigV4 authentication

jmespath/src/main/java/software/amazon/smithy/java/jmespath/JMESPathFunction.java, jmespath/src/test/java/software/amazon/smithy/java/jmespath/ComplianceTestRunner.java
=> Add JMESPath to_number function

README.md
=> Update init call

mcp/mcp-bundle-api/src/main/resources/META-INF/smithy/mcpbundle.smithy
* Rebase of https://github.com/smithy-lang/smithy-java/pull/683
* Also adding extra slash for correct Smithy comment
=> Adding CodeRepoBundle

mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServer.java
=> Add service name suffix to tool operation name

client/client-rulesengine/build.gradle.kts, client/client-rulesengine/src/main/java/software/amazon/smithy/java/client/rulesengine/ContextProvider.java, client/client-rulesengine/src/main/java/software/amazon/smithy/java/client/rulesengine/EndpointRulesResolver.java, client/client-rulesengine/src/main/java/software/amazon/smithy/java/client/rulesengine/EndpointUtils.java, client/client-rulesengine/src/test/java/software/amazon/smithy/java/client/rulesengine/EndpointRulesResolverTest.java, client/client-rulesengine/src/test/java/software/amazon/smithy/java/client/rulesengine/EndpointUtilsTest.java, client/client-rulesengine/src/test/java/software/amazon/smithy/java/client/rulesengine/RulesCompilerTest.java, client/client-rulesengine/src/test/resources/software/amazon/smithy/java/client/rulesengine/runner/default-values.smithy, client/client-rulesengine/src/test/resources/software/amazon/smithy/java/client/rulesengine/runner/ruleset-with-params.smithy
=> Add context param providers

buildSrc/settings.gradle, settings.gradle.kts
This is required to use this project in Gradle composite builds 
=> Explicity configure plugin repositories for Gradle composite builds to work

examples/lambda/build.gradle.kts
=> Use JDK21 in the examples Lambda

mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/ProcessIoProxy.java
=> Do not create proxy threads if IO is StdIo

model-bundle/model-bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ModelBundles.java, server/server-proxy/src/main/java/software/amazon/smithy/java/server/ProxyService.java
Additionally, set a default value of mcp-proxy for the MCP proxy client.
=> Allow customization of the proxy client's user agent

mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/ProcessIoProxy.java, mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/StartServer.java
StartServer is no more waiting in the main thread, so we need something similar for ProcessIoProxy
=> Add awaitCompletion in ProcessIoProxy

aws/aws-mcp-cli-commands/src/main/java/software/amazon/smithy/java/aws/mcp/cli/commands/AddAwsServiceBundle.java, aws/aws-service-bundler/src/main/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundler.java, aws/aws-service-bundler/src/test/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundlerTest.java, model-bundle/model-bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ModelBundles.java
=> Add option to filter operations in AwsServiceBundler

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
=> Enabling pretty printing for ConfigUtils json codec

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java, mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/McpCliVersionProvider.java, mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/VersionProvider.java
=> Add version provider SPI

mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/ListBundles.java
=> Add installed tag to already installed servers

aws/aws-mcp-cli-commands/build.gradle.kts, mcp/mcp-cli-api/build.gradle.kts, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/SmithyMcpCommand.java, mcp/mcp-cli/build.gradle.kts, mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/ListBundles.java
=> Generate graal metadata for CLIs

examples/lambda/README.md
=> Fix lambda template name in README

mcp/mcp-bundle-api/src/main/resources/META-INF/smithy/mcpbundle.smithy, mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/InstallBundle.java
=> Add ability to generic bundle to be executed directly

mcp/mcp-bundle-api/src/main/resources/META-INF/smithy/mcpbundle.smithy, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java, mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/UninstallBundle.java
=> Handle multiple install commands

codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborConstants.java, codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborDeserializer.java, codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborReadUtil.java, codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborSerializer.java, codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/Sink.java, codecs/cbor-codec/src/test/java/software/amazon/smithy/java/cbor/CborParserTest.java, codecs/cbor-codec/src/test/java/software/amazon/smithy/java/cbor/CborSerializerTest.java, codecs/cbor-codec/src/test/java/software/amazon/smithy/java/cbor/CborTestData.java
=> Add support for BigDecimals and BigInteger in RpcV2 Cbor

mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/ListBundles.java
=> Add a println after printing the description

.claude/settings.local.json
=> Give Claude code permissions to read, list, grep and execute gradle tasks for this project

aws/aws-service-bundler/src/main/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundler.java, aws/aws-service-bundler/src/test/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundlerTest.java, model-bundle/model-bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ModelBundler.java
=> Remove unused shapes while creating the bundle

codegen/codegen-core/src/main/java/software/amazon/smithy/java/codegen/generators/ResourceGenerator.java
Change requested in #799 but was merged too early
=> Use map's symbol reference in ResourceGenerator

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
=> Allow passing a test user home

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
=> Instead of rewriting all lines, just append

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/AbstractCreateBundle.java
=> Minor fixes to messages and error in AbstractCreateBundle

aws/aws-mcp-cli-commands/src/main/java/software/amazon/smithy/java/aws/mcp/cli/AwsMcpRegistry.java, mcp/mcp-bundle-api/src/main/java/software/amazon/smithy/mcp/bundle/api/Registry.java, mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/InstallBundle.java, mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/UninstallBundle.java
=> Handle null bundle returned from the registry and improve messages

mcp/mcp-cli-api/build.gradle.kts, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/CliMetrics.java, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ExecutionContext.java, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/SmithyMcpCommand.java, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/TelemetryPublisher.java, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/TelemetryPublisherProvider.java, mcp/mcp-cli-api/src/main/resources/META-INF/smithy/manifest, mcp/mcp-cli-api/src/main/resources/META-INF/smithy/mcp-cli-api.smithy
=> Add Cli Telemetry

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/CliMetrics.java, mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/SmithyMcpCommand.java, mcp/mcp-cli-api/src/main/resources/META-INF/smithy/mcp-cli-api.smithy
=> Add exit code and change name of Time metric

mcp/mcp-cli-api/src/main/resources/META-INF/smithy/mcp-cli-api.smithy
- **Make exit code PrimitiveInteger**
=> Make exit code PrimitiveInteger

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
=> Do not create a wrapper for generic bundles for now

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
Some install commands have additional instructions even for successful installations that we are currently hiding. We only print when there is an error.
Changing to print all the time.
=> Print out install command output

client/client-mock-plugin/src/main/java/software/amazon/smithy/java/client/http/mock/MockService.java, codegen/codegen-core/src/main/java/software/amazon/smithy/java/codegen/generators/SchemaIndexGenerator.java, codegen/plugins/client-codegen/src/main/java/software/amazon/smithy/java/codegen/client/DirectedJavaClientCodegen.java, codegen/plugins/server-codegen/src/main/java/software/amazon/smithy/java/codegen/server/DirectedJavaServerCodegen.java, codegen/plugins/server-codegen/src/main/java/software/amazon/smithy/java/codegen/server/ServerSymbolProperties.java, codegen/plugins/server-codegen/src/main/java/software/amazon/smithy/java/codegen/server/ServiceJavaSymbolProvider.java, codegen/plugins/server-codegen/src/main/java/software/amazon/smithy/java/codegen/server/generators/ServiceGenerator.java, codegen/plugins/types-codegen/src/main/java/software/amazon/smithy/java/codegen/types/DirectedJavaTypeCodegen.java, codegen/plugins/types-codegen/src/test/java/software/amazon/smithy/java/codegen/types/CodegenTest.java, core/src/main/java/software/amazon/smithy/java/core/schema/SchemaIndex.java, dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/SchemaConverter.java, examples/standalone-types/src/test/java/software/amazon/smithy/java/example/SchemaIndexTest.java, mcp/mcp-schemas/build.gradle.kts, server/server-api/src/main/java/software/amazon/smithy/java/server/FilteredService.java, server/server-api/src/main/java/software/amazon/smithy/java/server/Service.java, server/server-api/src/test/java/software/amazon/smithy/java/server/FilteredServiceTest.java, server/server-core/src/test/java/software/amazon/smithy/java/server/core/TestStructs.java, server/server-proxy/src/main/java/software/amazon/smithy/java/server/ProxyService.java
=> Generate SchemaIndex to support fetching Schema's from ShapeId

core/src/main/java/software/amazon/smithy/java/core/schema/SchemaIndex.java, mcp/mcp-schemas/build.gradle.kts, mcp/mcp-schemas/model/tool-assistant.smithy, mcp/mcp-schemas/smithy-build.json, mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/PromptLoader.java
=> Add @tool_assistant and @install_tool prompts

codegen/codegen-core/src/main/java/software/amazon/smithy/java/codegen/CodeGenerationContext.java, codegen/codegen-core/src/test/java/software/amazon/smithy/java/codegen/CodegenContextTest.java
It would be nice to bake this into the trait SPI directly instead of maintaining the static list.
=> Add 'smithy.ai#prompts' as a default runtime trait'

codegen/codegen-core/src/it/java/software/amazon/smithy/java/codegen/test/ExceptionsTest.java, codegen/codegen-core/src/it/resources/META-INF/smithy/exceptions/exception-tests.smithy, codegen/codegen-core/src/main/java/software/amazon/smithy/java/codegen/generators/StructureGenerator.java
=> Fix message in generated exceptions when the message field has a different casing

mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/ListBundles.java
=> Enable fallback to dumb terminal

framework-errors/src/main/java/software/amazon/smithy/framework/knowledge/ImplicitErrorIndex.java
The non-deterministic ordering of Shapes returned by getImplicitErrorsForService causes the TypeRegistry to be generated differently across runs. Since code generation should always be deterministic, producing identical output for the same model, this behavior is problematic.
=> Make ImplicitErrorIndex immutable and deterministic

client/client-http/src/main/java/software/amazon/smithy/java/client/http/HttpClientDataStream.java
Check that we have demand before requesting from upstream.
=> Check that we have demand before requesting from upstream.

model-bundle/model-bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ModelBundles.java, model-bundle/model-bundle-api/src/test/java/software/amazon/smithy/modelbundle/api/ModelBundlesTest.java
=> Generate an input shape with additionalInput member for operations with Unit input
