smithy-lang/smithy-java

client/client-core/src/main/java/software/amazon/smithy/java/client/core/ClientPipeline.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/ClientTransport.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/error/ConnectTimeoutException.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/error/ConnectionAcquireTimeoutException.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/error/ConnectionClosedException.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/error/TlsException.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/error/TransportException.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/error/TransportProtocolException.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/error/TransportSocketException.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/error/TransportSocketTimeout.java
client/client-core/src/test/java/software/amazon/smithy/java/client/core/ClientTest.java
client/client-http/src/main/java/software/amazon/smithy/java/client/http/JavaHttpClientTransport.java

To avoid directly exposing the exceptions of the underlying transport of a ClientTransport, which inadvertently allows for coupling of caller logic to a specific transport, we now provide a set of transport exceptions that extend from CallException.
ClienTransports are expected to only throw a subtype of CallException or ClienTransportException, and to wrap other exceptions. ClientPipeline has been updated to also perform this remapping in case a transport either is implemented incorrectly or tries to work around this mapping (which again allows for coupling to a specific transport).

Add our own exceptions for ClientTransport

---

client/dynamic-client/build.gradle.kts
client/dynamic-client/src/main/java/software/amazon/smithy/java/dynamicclient/DocumentException.java
client/dynamic-client/src/main/java/software/amazon/smithy/java/dynamicclient/DynamicClient.java
client/dynamic-client/src/main/java/software/amazon/smithy/java/dynamicclient/DynamicOperation.java
client/dynamic-client/src/test/java/software/amazon/smithy/java/dynamicclient/DynamicOperationTest.java
config/spotbugs/filter.xml
dynamic-schemas/README.md
dynamic-schemas/build.gradle.kts
dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/SchemaConverter.java
dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/SchemaGuidedDocumentBuilder.java
dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/SchemaInterceptingSerializer.java
dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/WrappedDocument.java
dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/package-info.java
dynamic-schemas/src/test/java/software/amazon/smithy/java/dynamicschemas/SchemaConverterTest.java
dynamic-schemas/src/test/java/software/amazon/smithy/java/dynamicschemas/SchemaGuidedDocumentBuilderTest.java
dynamic-schemas/src/test/java/software/amazon/smithy/java/dynamicschemas/SchemaInterceptingSerializerTest.java
dynamic-schemas/src/test/java/software/amazon/smithy/java/dynamicschemas/WrappedDocumentTest.java
settings.gradle.kts

Various teams need to be able to access the underlying Shape->Schema conversion and WrappedDocuments.

Make dynamic schema conversion public

---

aws/client/aws-client-awsjson/src/it/java/software/amazon/smithy/java/client/aws/jsonprotocols/AwsJson1ProtocolTests.java
aws/client/aws-client-restjson/src/it/java/software/amazon/smithy/java/client/aws/restjson/RestJson1ProtocolTests.java
aws/client/aws-client-restxml/src/it/java/software/amazon/smithy/java/aws/client/restxml/RestXmlProtocolTests.java
aws/server/aws-server-restjson/src/it/java/software/amazon/smithy/java/server/protocols/restjson/AwsRestJson1ProtocolTests.java
client/client-rpcv2-cbor/src/it/java/software/amazon/smithy/java/client/rpcv2/RpcV2CborProtocolTests.java
protocol-test-harness/src/main/java/software/amazon/smithy/java/protocoltests/harness/ProtocolTestExtension.java

There was a minor bug in https://github.com/smithy-lang/smithy-java/pull/474 which causes the tests to not run. This is why https://github.com/smithy-lang/smithy-java/pull/548/ and https://github.com/smithy-lang/smithy-java/pull/549/ was able to remove these tests. 
Fixed the issue and added these back.

Really enable exception response tests

---

codegen/core/src/it/java/software/amazon/smithy/java/codegen/test/RecursionTests.java
codegen/core/src/main/java/software/amazon/smithy/java/codegen/generators/SchemasGenerator.java
core/src/main/java/software/amazon/smithy/java/core/schema/DeferredRootSchema.java
core/src/main/java/software/amazon/smithy/java/core/schema/ResolvedRootSchema.java
core/src/main/java/software/amazon/smithy/java/core/schema/Schema.java
core/src/main/java/software/amazon/smithy/java/core/schema/SchemaBuilder.java

Now that we have centralized the Schemas in a single class, this gives us a hook to also resolve them eagerly. Doing this avoids having to do volatile reads at runtime.
DynamicSchemas however still need a volatile read, since we don't have a similar hook for them.

Eagerly resolve deferred schemas

---

codegen/core/src/main/java/software/amazon/smithy/java/codegen/CodegenUtils.java
codegen/core/src/main/java/software/amazon/smithy/java/codegen/SymbolProperties.java
codegen/core/src/main/java/software/amazon/smithy/java/codegen/generators/ServiceExceptionGenerator.java
codegen/core/src/main/java/software/amazon/smithy/java/codegen/generators/StructureGenerator.java
codegen/plugins/client/src/main/java/software/amazon/smithy/java/codegen/client/ClientJavaSymbolProvider.java
codegen/plugins/client/src/main/java/software/amazon/smithy/java/codegen/client/DirectedJavaClientCodegen.java
codegen/plugins/server/src/main/java/software/amazon/smithy/java/codegen/server/DirectedJavaServerCodegen.java
codegen/plugins/server/src/main/java/software/amazon/smithy/java/codegen/server/ServiceJavaSymbolProvider.java
protocol-test-harness/src/main/java/software/amazon/smithy/java/protocoltests/harness/MockClient.java

Generating types for a client or server now will also generate a root-level exception for the service extending from ModeledException. This is not generated when using external types. This allows for catching exceptions of a specific service. However, framework and implicit exceptions are not part of this hierarchy.

Add root-level service exception

---

dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/SchemaGuidedDocumentBuilder.java
dynamic-schemas/src/test/java/software/amazon/smithy/java/dynamicschemas/SchemaGuidedDocumentBuilderTest.java

We were passing in target for all nested members, which isn't correct since the nested members need to actually use the right members schema. This is important for things like JSON deserialization that relies on JSON name.

Fix dynamic schema nested member deser

---

core/src/main/java/software/amazon/smithy/java/core/serde/TypeRegistry.java
core/src/test/java/software/amazon/smithy/java/core/serde/TypeRegistryTest.java

When registering a lot of classes in a type registry, you don't want to eagerly load all the classes up front. This would pull in virtually the entire graph of the model at startup.
This adds an alternative, albeit more cumbersome, API to register classes and builders with a type registry that only eagerly loads classes on first use by putting them into Suppliers.

Add a way to register classes without eager load

---

.github/workflows/ci.yml

- At some point, integ tests were removed from CI (or they were never added in the first place)
- [One test](https://github.com/smithy-lang/smithy-java/blob/main/examples/event-streaming-client/src/it/java/software/amazon/smithy/java/example/eventstreaming/EventStreamTest.java#L29) is disabled currently, it should be fixed whenever possible

Add integration tests to CI

---

codecs/json-codec/src/main/java/software/amazon/smithy/java/json/JsonDocuments.java
codecs/json-codec/src/test/java/software/amazon/smithy/java/json/JsonDocumentTest.java

I discovered that we can't serialize Document maps with null values while implementing CBOR documents. This uses the same approach that we're using in JsonDocuments$ListSerializer.
Fun fact: the JVM generates terrible stack traces when the receiver for an instance method reference is null. The reference `Document::serializeContents` throws a NPE from a synthetic method when the `Document` having its `serializeContents` method invoked is null. You can see that the param in the first argument slot is null in the debugger and infer what's going on, but debugging runtime-generated code is always a nightmare.

Fix Document serialization of maps with null values

---

.github/workflows/ci.yml

This reverts commit a80e657460b492a7fe6ad154109244609e54eb11.
Temporarily revert running integ tests while they're failing on CI

Revert "Add integration tests to CI"

---

client/client-core/src/main/java/software/amazon/smithy/java/client/core/Client.java

The accidental use of `config` instead of `callConfig` previously made it impossible to specify overrides for either of these options through the RequestOverrideConfig API.

Use interceptors and identity resolvers from request overrides when present

---

buildSrc/src/main/kotlin/smithy-java.module-conventions.gradle.kts
examples/lambda/build.gradle.kts
examples/standalone-types/build.gradle.kts
framework-errors/build.gradle.kts

- Because the generated code is flat (no `src/main/java` and `src/main/resources`), the same source directory was being set
- This was also explicitly called out in the TODO removed in this PR
- Some zip implementations will fail to unzip when there are duplicate entries
- Adds a fail duplicate strategy to our `module-conventions` plugin so this doesn't happen in the future
*Before*
```
META-INF/
META-INF/LICENSE
META-INF/MANIFEST.MF
META-INF/NOTICE
META-INF/services/
META-INF/services/software.amazon.smithy.model.traits.TraitService
META-INF/smithy-java/
META-INF/smithy-java/type-mappings.properties
META-INF/smithy-java/type-mappings.properties
META-INF/smithy/
META-INF/smithy/errors.smithy
META-INF/smithy/manifest
META-INF/smithy/trait.smithy
errors.smithy …
```

Fix sourceSets configuration for packages using type-codegen

---

client/dynamic-client/src/main/java/software/amazon/smithy/java/dynamicclient/DocumentException.java
client/dynamic-client/src/main/java/software/amazon/smithy/java/dynamicclient/DynamicOperation.java
codecs/json-codec/src/main/java/software/amazon/smithy/java/json/JsonSettings.java
core/src/main/java/software/amazon/smithy/java/core/schema/TraitKey.java
examples/mcp-server/README.md
examples/mcp-server/build.gradle.kts
examples/mcp-server/license.txt
examples/mcp-server/settings.gradle.kts
examples/mcp-server/smithy-build.json
examples/mcp-server/src/main/java/software/amazon/smithy/java/example/server/mcp/MCPServerExample.java
examples/mcp-server/src/main/java/software/amazon/smithy/java/example/server/mcp/ProxyMCPExample.java
examples/mcp-server/src/main/java/software/amazon/smithy/java/example/server/mcp/operations/GetCodingStatistics.java
examples/mcp-server/src/main/java/software/amazon/smithy/java/example/server/mcp/operations/GetEmployeeDetails.java
examples/mcp-server/src/main/resources/software/amazon/smithy/java/example/server/mcp/main.smithy
mcp/mcp-schemas/build.gradle.kts
mcp/mcp-schemas/license.txt
mcp/mcp-schemas/model/main.smithy
mcp/mcp-schemas/smithy-build.json
server/server-mcp/build.gradle.kts
server/server-mcp/src/main/java/software/amazon/smithy/java/server/mcp/MCPServer.java
server/server-mcp/src/main/java/software/amazon/smithy/java/server/mcp/MCPServerBuilder.java
server/server-proxy/build.gradle.kts
server/server-proxy/src/main/java/software/amazon/smithy/java/server/ProxyService.java
settings.gradle.kts
smithy-templates.json

Adds MCP support to smithy-java. Users can now do 2 things,
1. Generate an MCP server for their existing service implementation.
2. Generate a MCP Proxy server for any service with just the smithy model.

Add MCP Support

---

.github/workflows/ci.yml

Windows builds are terribly slow and slow development. Removing it for now. Created a backlog task #640 to re-nable it.

Remove windows from the CI for now

---

.github/workflows/ci.yml
codegen/plugins/client-codegen/src/main/java/software/amazon/smithy/java/codegen/client/generators/ClientInterfaceGenerator.java
examples/restjson-client/src/it/java/software/amazon/smithy/java/example/ClientConfigTest.java

The integration tests are failing because the service schemas wasn't set in the client config. We were incorrectly setting this only when auth schemes exist.

Fix integration tests

---

model-bundler/bundle-api/build.gradle.kts
model-bundler/bundle-api/license.txt
model-bundler/bundle-api/model/bundle.smithy
model-bundler/bundle-api/smithy-build.json
model-bundler/bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ConfigProvider.java
model-bundler/bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ConfigProviderFactory.java
model-bundler/bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ConfigProviders.java
model-bundler/bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/StaticAuthSchemeResolver.java
settings.gradle.kts

To be used by the MCP server bundle consumer. The AWS service bundler is ready to go but depends on another to-be-published PR.

Add model bundle API

---

codecs/json-codec/src/main/java/software/amazon/smithy/java/json/JsonDocuments.java
codecs/json-codec/src/test/java/software/amazon/smithy/java/json/JsonDocumentTest.java
core/src/main/java/software/amazon/smithy/java/core/serde/document/Document.java

The Document impls in JsonDocuments are records, so their default `equals` methods check that all the record members are equal. Since they all contain JsonSettings members, two JsonDocuments are only equal if they have the exact same JsonSettings instance.

Fix JsonDocuments equals implementation

---

core/src/main/java/software/amazon/smithy/java/core/schema/ApiOperation.java
server/server-api/build.gradle.kts
server/server-api/src/main/java/software/amazon/smithy/java/server/FilteredService.java
server/server-api/src/main/java/software/amazon/smithy/java/server/OperationFilters.java
server/server-api/src/test/java/software/amazon/smithy/java/server/FilteredServiceTest.java
server/server-api/src/test/java/software/amazon/smithy/java/server/OperationFiltersTest.java
server/server-api/src/test/java/software/amazon/smithy/java/server/TestStructs.java

Add ability to create a filtered service which only exposes certain operations of a service.

Add Operation filtering

---

core/src/main/java/software/amazon/smithy/java/core/serde/Codec.java

We also don't need to call flush since it's done when calling close

Ensure serializer is closed

---

codecs/cbor-codec/build.gradle.kts
codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborDeserializer.java
codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborDocuments.java
codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborSerdeProvider.java
codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborSerializer.java
codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/CborSettings.java
codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/DefaultCborSerdeProvider.java
codecs/cbor-codec/src/main/java/software/amazon/smithy/java/cbor/Rpcv2CborCodec.java
codecs/cbor-codec/src/test/java/software/amazon/smithy/java/cbor/CborDocumentTest.java
codecs/cbor-codec/src/test/java/software/amazon/smithy/java/cbor/CborSerializerTest.java

Adds Document support to CBOR and the RPCv2 CBOR protocol. Does not add BigNum support.
#603

Add Document support to RPCv2 CBOR

---

aws/client/aws-client-awsjson/src/main/java/software/amazon/smithy/java/aws/client/awsjson/AwsJsonProtocol.java
aws/client/aws-client-restjson/src/main/java/software/amazon/smithy/java/aws/client/restjson/RestJsonClientProtocol.java
aws/client/aws-client-restxml/src/main/java/software/amazon/smithy/java/aws/client/restxml/RestXmlClientProtocol.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/ClientProtocol.java
client/client-http-binding/src/main/java/software/amazon/smithy/java/client/http/binding/HttpBindingClientProtocol.java
client/client-mock-plugin/src/main/java/software/amazon/smithy/java/client/http/mock/MockPlugin.java
client/client-rpcv2-cbor/src/main/java/software/amazon/smithy/java/client/rpcv2/RpcV2CborProtocol.java
protocol-test-harness/src/main/java/software/amazon/smithy/java/protocoltests/harness/MockClient.java

ClientProtocol now exposes a payloadCoded method that can be used to get the Codec configured for the protocol. So a RestJson1 protocol would be able to return Codec configured to correctly serialize and deserialize RestJSON1 payloads. If a protocol ever comes along that has no payload codec or perhaps multiple, null may be returned.

Add payloadCodec to ClientProtocol

---

aws/client/aws-client-restjson/src/it/java/software/amazon/smithy/java/client/aws/restjson/RestJson1ProtocolTests.java
http/http-binding/src/main/java/software/amazon/smithy/java/http/binding/HttpHeaderListDeserializer.java

We're splitting based on commas and quotes, but were including quotes as part of each parsed value. The quotes shouldn't be part of the parsed value, and removing it fixes a restJson1 protocol test.

Fix CSV header parsing to not include quotes

---

cli/src/main/java/software/amazon/smithy/java/cli/SmithyCall.java

We can't bring foreign traits to the CLI right now, so we have no choice but to ignore them.

Ignore unknown traits in SmithyCall

---

examples/restjson-client/build.gradle.kts
examples/restjson-client/src/main/java/software/amazon/smithy/java/example/ClientExample.java

Our integ tests randomly fail when httpbin.org starts rate-limiting us.

Avoid calling external services in our integration tests

---

cli/src/main/java/software/amazon/smithy/java/cli/SmithyCall.java

Added FINE level logging for SigV4 configuration.

Add logging to display signing name used for sigv4 auth.

---

client/client-core/src/main/java/software/amazon/smithy/java/client/core/Client.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/ClientCall.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/interceptors/CallHook.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/interceptors/ClientInterceptor.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/interceptors/ClientInterceptorChain.java
client/client-core/src/test/java/software/amazon/smithy/java/client/core/ClientTest.java

Interceptors now have a new hook, modifyBeforeCall that accepts the ApiOperation being called, input of the call, and ClientConfig. It is expected to return the same ClientConfig or an updated ClientConfig using ClientConfig#withRequestOverride.
This allows for much more dynamic calls with clients, like changing the protocol per/call, applying plugins per/call, and more.

Add ability to override call config in interceptor

---

server/server-api/build.gradle.kts

When compiling a project that uses the server-rpcv2-cbor package we get an error that Exception classes declared in the framework-error package cannot be found. server-rpcv2-cbor declares an api dependency on server-api which is a common package for server related code. If framework-errors are intended to be common server logic then server-api should declare an api dependency on framework-errors so that consumers will be able to access those classes (which are used in code generation).
An alternative is to declare that api dependency on framework-errors in the server-rpcv2-cbor package; however, considering that these errors are intended to be common across server implementations, it should ostensibly go in the the common server-api package.

Expose framework error classes to server dependencies

---

README.md

Weirdest rendering ever, but it makes sense since it's a "diff" snippet:

Fix plugin dependency in README

---

codegen/codegen-core/src/main/java/software/amazon/smithy/java/codegen/generators/SchemaFieldOrder.java
codegen/codegen-core/src/main/java/software/amazon/smithy/java/codegen/generators/SchemasGenerator.java
codegen/codegen-core/src/main/java/software/amazon/smithy/java/codegen/integrations/externaltypes/ExternalTypesIntegration.java
examples/standalone-types/build.gradle.kts
examples/standalone-types/model/person.smithy
examples/standalone-types/src/test/java/software/amazon/smithy/java/example/ExternalTypesTest.java
jmespath/src/main/java/software/amazon/smithy/java/jmespath/JMESPathFunction.java
jmespath/src/test/java/software/amazon/smithy/java/jmespath/ComplianceTestRunner.java

We should not re-generate schema in our Schema's class for external types. This currently only does it for external structures but not external list/maps.

Don't regenerate Schemas of external types

---

aws/aws-mcp-cli-commands/src/main/java/software/amazon/smithy/java/aws/mcp/cli/commands/AddAwsServiceBundle.java
mcp/mcp-bundle-api/src/main/resources/META-INF/smithy/mcpbundle.smithy

We need MCP specific information in the McpBundle structure, so having the SmithyBundle directly as a Union member doesn't work.

Add a wrapper structure over the SmithyBundle to capture mcp specific information

---

client/client-core/src/main/java/software/amazon/smithy/java/client/core/CallContext.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/Client.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/ClientCall.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/ClientConfig.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/ClientContext.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/endpoint/Endpoint.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/endpoint/EndpointContext.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/endpoint/EndpointResolver.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/endpoint/StaticHostResolver.java
client/client-core/src/test/java/software/amazon/smithy/java/client/core/ClientTest.java
client/client-http/src/main/java/software/amazon/smithy/java/client/http/plugins/UserAgentPlugin.java
client/client-http/src/test/java/software/amazon/smithy/java/client/http/plugins/UserAgentPluginTest.java
client/client-rulesengine/src/main/java/software/amazon/smithy/java/client/rulesengine/EndpointRulesPlugin.java
client/client-rulesengine/src/main/java/software/amazon/smithy/java/client/rulesengine/EndpointRulesResolver.java
client/client-rulesengine/src/main/java/software/amazon/smithy/java/client/rulesengine/RulesVm.java
client/client-rulesengine/src/main/java/software/amazon/smithy/java/client/rulesengine/Stdlib.java
client/client-rulesengine/src/test/java/software/amazon/smithy/java/client/rulesengine/EndpointRulesPluginTest.java
client/client-rulesengine/src/test/java/software/amazon/smithy/java/client/rulesengine/RulesCompilerTest.java
client/client-rulesengine/src/test/java/software/amazon/smithy/java/client/rulesengine/RulesVmTest.java
client/client-rulesengine/src/test/java/software/amazon/smithy/java/client/rulesengine/StdlibTest.java

Client builder now has new `endpoint` builder methods that are used to more easily set a custom endpoint for the client. This also sets the ClientContext.CUSTOM_ENDPOINT setting that the rules engine plugin looks for two (1) know if it should override the currently set endpoint provider of the client (2) what the SDK::Endpoint builtin should return when called.
This commit also breaks up some of the context properties that were all stored in CallContext and moves some that can be client-wide to ClientContext.

Add a way to set CUSTOM_ENDPOINT and use with EP 2

---

codecs/cbor-codec/src/test/java/software/amazon/smithy/java/cbor/CborDocumentTest.java
codecs/json-codec/src/test/java/software/amazon/smithy/java/json/JsonDocumentTest.java
core/src/main/java/software/amazon/smithy/java/core/serde/TypeRegistry.java
core/src/main/java/software/amazon/smithy/java/core/serde/document/Document.java
core/src/main/java/software/amazon/smithy/java/core/serde/document/DocumentDeserializer.java
core/src/test/java/software/amazon/smithy/java/core/serde/document/DocumentDeserializerTest.java
core/src/test/java/software/amazon/smithy/java/core/serde/document/DocumentTest.java
dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/StructDocument.java
dynamic-schemas/src/test/java/software/amazon/smithy/java/dynamicschemas/StructDocumentTest.java

Document#discriminator is now nullable, and returns null if no discriminator is found. This method still throws if a string is found but cannot be parsed. Making this nullable allows us to compose type registries so that they can check multiple registries to attempt to create a builder for a document.
Added a new api to TypeRegistry: createBuilder(Document). This API attempts to find a builder for a document based on its discriminator or returns null if the document has none, or no matching builder is found. This matches the behavior of createBuilder(ShapeId).
Added a new api to TypeRegistry: deserializeString(Document). This API deserializes a document into a builder from the registry but does not use error correction, ensuring that missing defaults are not filled in with zero values, …

Make Document#discriminator nullable, add registry

---

mcp/mcp-schemas/model/main.smithy

This is not guaranteed to be present for MCP servers because documentation traits are optional

Make PropertyDetails#description optional

---

mcp/mcp-bundle-api/src/main/resources/META-INF/smithy/mcpbundle.smithy

Replace CodeRepoBundle with GenericBundle.

Adding GenericBundle

---

codecs/json-codec/src/main/java/software/amazon/smithy/java/json/JsonCodec.java
codecs/json-codec/src/main/java/software/amazon/smithy/java/json/JsonSettings.java
codecs/json-codec/src/main/java/software/amazon/smithy/java/json/jackson/JacksonJsonSerializer.java
codecs/json-codec/src/test/java/software/amazon/smithy/java/json/JsonSerializerTest.java

- Adds a new  option to JsonSettings that can be used to format JSON output with indentation and line breaks
- The option is disabled by default to maintain backward compatibility
- Adds a test case to verify pretty printing functionality

Add pretty printing support to JSON serialization

---

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
mcp/mcp-cli/build.gradle.kts
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/StartServer.java
mcp/mcp-schemas/build.gradle.kts
mcp/mcp-schemas/model/registry.smithy
mcp/mcp-schemas/smithy-build.json
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServer.java

This change serves the local registry itself as an MCP server, allowing tools to be dynamically located and installed during a session. To support this, we now support the `listChanged` server capability.
Additionally, I fixed a bug in ConfigUtils that did not cause the local registry to be updated on installation.

Add dynamic tool loading

---

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/AbstractAddBundle.java
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ExecutionContext.java
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/RegistryUtils.java
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/SmithyMcpCommand.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/InstallBundle.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/ListBundles.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/StartServer.java

The registry selection just returned the first registry it found incorrectly instead of picking the default configured registry.
Also simplified the registry selection process by pulling it in to a single place.

Fix Registry selection, inject Registry into the command

---

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/SmithyMcpCommand.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/ListBundles.java

Improve formatting of mcp-registry list output

---

mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/SmithyMcpCommand.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/StartServer.java
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServer.java

For some reason, Q chat isn't attempting to terminate our process when it exits. [It looks like it should](https://github.com/aws/amazon-q-developer-cli/blob/main/crates/cli/src/util/process/unix.rs#L6), but [they also expect local servers that are "implemented well" to exit when the input pipe closes](https://github.com/aws/amazon-q-developer-cli/blob/main/crates/cli/src/mcp_client/client.rs#L205-L206). We will now follow that expectation.

Shut down local MCP server when the client disconnects

---

mcp/mcp-bundle-api/src/main/resources/META-INF/smithy/mcpbundle.smithy
mcp/mcp-cli-api/model/main.smithy
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/ProcessIoProxy.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/StartServer.java

Add support for starting generic mcp server configs. Till we implement the full MCP spec in MCPServerProxy we can only start a single proxy server.

Add support for starting an McpServer from a GenericBundle

---

buildSrc/src/main/kotlin/smithy-java.java-conventions.gradle.kts

This makes jars reproducible to an extent. Spot checked MD5 sum of some jars remain same across clean builds and on different machines.

Make jars reproducible

---

aws/aws-service-bundler/src/main/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundler.java
aws/aws-service-bundler/src/test/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundlerTest.java

Now, we input the sigv4 signing name to the bundler and use that to produce the bundles. This doesn't _exactly_ align with the experience we want but it's closer than we were before.

Resolve AWS services in the AWS bundler by sigv4 signing name

---

mcp/mcp-cli-api/model/main.smithy
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/McpCli.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/InstallBundle.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/UninstallBundle.java

Introduces an UninstallBundle command that allows users to remove previously installed MCP bundles from their configuration. The command removes bundle entries from configuration files and updates client configs as needed. Complements the existing InstallBundle command to provide complete bundle lifecycle management.

Add uninstall command

---

aws/aws-service-bundle/src/main/java/software/amazon/smithy/java/aws/servicebundle/provider/AwsServiceBundle.java
aws/aws-service-bundler/src/test/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundlerTest.java
client/dynamic-client/src/main/java/software/amazon/smithy/java/dynamicclient/DynamicClient.java

Notably, this adds getter methods to the DynamicClient builder for `model` and `service`.

Default to aws-json-1.0 for AWS services with unsupported protocols

---

mcp/mcp-schemas/model/main.smithy
mcp/mcp-server/build.gradle.kts
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServer.java
mcp/mcp-server/src/test/java/software/amazon/smithy/java/mcp/server/McpServerTest.java
mcp/mcp-server/src/test/java/software/amazon/smithy/java/mcp/server/TestInputStream.java
mcp/mcp-server/src/test/java/software/amazon/smithy/java/mcp/server/TestOutputStream.java
server/server-proxy/src/main/java/software/amazon/smithy/java/server/ProxyService.java

```
{
"jsonrpc": "2.0",
"result": {
"tools": [
{
"name": "TestOperation",
"description": "This tool invokes TestOperation API of TestService.A TestOperation",
"inputSchema": {
"type": "object",
"properties": {
"str": {
"type": "string",
"description": "It's a string"
},
"nested": {
"type": "object",
"properties": {
"nestedStr": {
"type": "string",
"description": "A string that's nested"
}
},
"required": [],
"additionalProperties": false,
"description": "A structure that can be nested",
"$schema": "http://json-schema.org/draft-07/schema#"
}
},
"required": [],
"additionalProperties": false,
"description": "An input for TestOperation with a nested member",
"$schema": "http://json-schema.org/draft-07/schema#"
}
}
]
},
"id": 0
}
```

Render nested members in tool descriptions

---

mcp/mcp-server/src/test/java/software/amazon/smithy/java/mcp/server/TestOutputStream.java

Binary search is undefined on an unsorted array, and we always need to select the first newline

Fix TestOutputStream's newline finding

---

build.gradle.kts

Currently IntelliJ marks all the integration test sourcesets as source which messes with IntelliJ's 
code analysis tools like finding usages outside tests. 
After this change,

Mark integrationTest sourcesets as test in IntelliJ

---

.github/workflows/ci.yml

Our CI builds are too slow. The [avg build times are 14 and 17 mins](https://github.com/smithy-lang/smithy-java/actions/metrics/performance?tab=jobs). With this we will start storing Gradle caches in Github Action Caches.
[Example run](https://github.com/adwsingh/smithy-java/actions/runs/15460671192) from my fork with this change completed in 3m53s.
We also encrypt the caches to not leak any sensitive info that maybe produced during build.

Use gradle caches in CI

---

framework-errors/build.gradle.kts

This is required to make framework-errors jar reproducible. I checked the smithy-gradle plugin and these seem to be only informational. The Smithy-Tags attribute in the only relevant attribute in the manifest.

Remove fluctuating constants from jar manifest which is added by smithy jar task

---

aws/aws-service-bundler/src/main/java/software/amazon/smithy/java/aws/servicebundle/bundler/ApiStandardTerminology.java
aws/aws-service-bundler/src/main/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundler.java
aws/aws-service-bundler/src/test/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundlerTest.java

Datazone endpoints end in [.api.aws](https://github.com/aws/api-models-aws/blob/main/models/datazone/service/2018-05-10/datazone-2018-05-10.json#L9486) instead of `.amazonaws.com`. 
ApiStandardTerminology made public for testing and convenience.

Allow .api.aws endpoints

---

mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServer.java
mcp/mcp-server/src/test/java/software/amazon/smithy/java/mcp/server/McpServerTest.java

We coerce BigDecimal, BigInteger to Strings for MCP but we need to convert them back when calling the actual operation.

Handle types we coerce to Strings in MCP

---

mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/McpCli.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/McpRegistry.java

**Add a hook to add system properties to the Cli**

Add system property to allow host header to be added to HttpRequest

---

mcp/mcp-cli-api/model/main.smithy
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/DefaultConfigProvider.java
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/EmptyDefaultConfigProvider.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/ClientConfigCommand.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/Configure.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/StartServer.java

Add client-config command to configure client config

---

aws/aws-mcp-cli-commands/src/main/java/software/amazon/smithy/java/aws/mcp/cli/commands/AddAwsServiceBundle.java

See https://github.com/smithy-lang/smithy-java/pull/772#discussion_r2141268175

If allowedApis is provided respect that always

---

build.gradle.kts

- Nexus2 deployer is sunsetting on June 30th

Use JReleaser 'MavenCentral' deployer for releases

---

aws/aws-service-bundle/src/main/java/software/amazon/smithy/java/aws/servicebundle/provider/AwsServiceBundle.java
client/client-core/src/main/java/software/amazon/smithy/java/client/core/Client.java
client/client-core/src/test/java/software/amazon/smithy/java/client/core/ClientTest.java
model-bundle/model-bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ModelBundles.java
server/server-proxy/src/main/java/software/amazon/smithy/java/server/ProxyOperationTrait.java
server/server-proxy/src/main/java/software/amazon/smithy/java/server/ProxyService.java

Modifying the actual input model has other side affects like affecting RestJson serialization. To avoid these we now create proxy operations which delegate to the actual operations.

Handle additionalInput without modifying the actual input model

---

model-bundle/model-bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ModelBundles.java

Before #790, we weren’t removing unrelated services from the generated bundle model if they were present in the original model. We added a check in #787 to handle that, but any bundles created via the CLI before that change are now broken. So we're removing the check and instead assuming that the bundle model already contains the intended Service shape by ID.

Do not require the bundle model to have a single service

---

aws/aws-service-bundler/src/main/java/software/amazon/smithy/java/aws/servicebundle/bundler/AwsServiceBundler.java

After #790 we remove the unused shaped so PreRequest was getting removed from the main model. And we pack the incorrect model in additional input.

Fix model path for additional input in Aws bundles

---

model-bundle/model-bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/ModelBundles.java
model-bundle/model-bundle-api/src/main/java/software/amazon/smithy/modelbundle/api/PluginProviders.java

We previously only permitted JSON-serialized models.

Support smithy models in bundles

---

aws/aws-mcp-cli-commands/build.gradle.kts
aws/aws-mcp-cli-commands/src/main/java/software/amazon/smithy/java/aws/mcp/cli/commands/AddAwsServiceBundle.java
aws/aws-mcp-cli-commands/src/main/java/software/amazon/smithy/java/aws/mcp/cli/commands/CreateAwsServiceBundle.java
aws/aws-mcp-cli-commands/src/main/resources/META-INF/services/software.amazon.smithy.java.mcp.cli.AbstractCreateBundle
mcp/mcp-bundle-api/src/main/java/software/amazon/smithy/mcp/bundle/api/ModifiableRegistry.java
mcp/mcp-bundle-api/src/main/resources/META-INF/smithy/mcpbundle.smithy
mcp/mcp-cli-api/build.gradle.kts
mcp/mcp-cli-api/model/main.smithy
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/AbstractCreateBundle.java
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ClientsInput.java
mcp/mcp-cli-api/src/main/java/software/amazon/smithy/java/mcp/cli/ConfigUtils.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/McpCli.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/Configure.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/CreateBundle.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/CreateGenericBundle.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/InstallBundle.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/ListBundles.java

- Add create command infrastructure with pluggable bundle creation support
- Implement local bundle concept to distinguish between registry and locally created bundles
- Add AWS service bundle creation via create aws-service-mcp subcommand
- Add generic MCP bundle creation via create generic-mcp subcommand

Add create command and have a concept of local bundles

---

examples/mcp-traits-example/README.md
examples/mcp-traits-example/build.gradle.kts
examples/mcp-traits-example/gradle.properties
examples/mcp-traits-example/model/main.smithy
examples/mcp-traits-example/settings.gradle.kts
examples/mcp-traits-example/smithy-build.json
gradle/libs.versions.toml
mcp/mcp-server/build.gradle.kts
mcp/mcp-traits/build.gradle.kts
mcp/mcp-traits/model/prompts.smithy
mcp/mcp-traits/smithy-build.json
settings.gradle.kts

This PR introduces a new @prompts trait that enables Smithy service authors to provide contextual guidance for Large Language Models (LLMs) when interacting with their services. The trait can be applied to services, resources, and operations to define prompt templates, parameter descriptions, and usage conditions.
The logic for using the data from the traits to serve prompts as part of the MCP server will be a separate PR.
Key features:
• **Prompt Templates**: Define template text with placeholders for parameters and multi-operation workflows
• **Parameter Guidance**: Optional argument descriptions to help LLMs understand parameter usage
• **Conditional Usage**: Specify when certain operations should be preferred over others
• **Flexible Application**: Can be applied at service, resource, …

Add a new module for  MCP specific traits with Prompts trait

---

examples/mcp-server/src/main/java/software/amazon/smithy/java/example/server/mcp/BundleMCPServerExample.java
examples/mcp-server/src/main/java/software/amazon/smithy/java/example/server/mcp/MCPServerExample.java
examples/mcp-server/src/main/java/software/amazon/smithy/java/example/server/mcp/ProxyMCPExample.java
mcp/mcp-bundle-api/src/main/java/software/amazon/smithy/mcp/bundle/api/RegistryTool.java
mcp/mcp-bundle-api/src/main/java/software/amazon/smithy/mcp/bundle/api/SearchableRegistry.java
mcp/mcp-cli/src/main/java/software/amazon/smithy/java/mcp/cli/commands/StartServer.java
mcp/mcp-schemas/model/main.smithy
mcp/mcp-schemas/model/registry.smithy
mcp/mcp-schemas/smithy-build.json
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServer.java
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServerBuilder.java
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServerProxy.java
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/PromptLoader.java
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/StdioProxy.java
mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/ToolFilter.java
mcp/mcp-server/src/test/java/software/amazon/smithy/java/mcp/server/McpServerTest.java

Add support for search tools and dynamic tool loading
This PR enhances the MCP server implementation with dynamic tool discovery and installation capabilities:
Key Changes
- Search Tools API: Added searchTools operation to the registry service that allows finding relevant tools based on task descriptions
- Dynamic Tool Installation: Implemented installTool operation to dynamically install MCP tools at runtime
- Tool Filtering: Added configurable tool filtering support with predicate-based filtering
- Server Architecture Updates:
- Services now stored in a map structure for better management
- Added support for both Smithy-modeled and generic MCP tool bundles
- Enhanced proxy server initialization and tool refresh mechanisms
- Registry …

Add support for search tools and dynamic tool loading

---

examples/mcp-server/build.gradle.kts
examples/mcp-server/smithy-build.json
examples/mcp-server/src/main/resources/software/amazon/smithy/java/example/server/mcp/main.smithy
examples/mcp-traits-example/README.md
examples/mcp-traits-example/build.gradle.kts
examples/mcp-traits-example/model/main.smithy
gradle/libs.versions.toml
mcp/mcp-server/build.gradle.kts
mcp/mcp-server/src/test/java/software/amazon/smithy/java/mcp/server/McpServerTest.java
mcp/mcp-server/src/test/resources/prompts/basic-prompt.smithy
settings.gradle.kts
smithy-ai-traits/build.gradle.kts
smithy-ai-traits/model/prompts.smithy
smithy-ai-traits/smithy-build.json

This PR contains  pending changes as discussed in #817 about placement of trait definition and the namespace so that future upstreaming to `smithy-lang/smithy` is easier.
• Renamed namespace from amazon.smithy.llm to smithy.ai in prompts trait definition
• Moved mcp/mcp-traits module to smithy-ai-traits to reflect the new namespace
• Updated all references across examples, tests, and build configurations
• Modified dependency declarations in gradle files and version catalog
- `./gradlew clean build`
- Validated that prompts list and get still works as before.

Move prompts trait to use `smithy.ai` namespace and`smithy-ai-traits` package for easier upstreaming.

---

dynamic-schemas/src/main/java/software/amazon/smithy/java/dynamicschemas/SchemaConverter.java
dynamic-schemas/src/test/java/software/amazon/smithy/java/dynamicschemas/SchemaConverterTest.java

I did not file an issue.
SchemaConverter would incorrectly identify member schemas as recursive when the shape graph contains multiple branches hitting the same target shape, downstream of the member shape.
This change "pops" the "top of stack" shape on the way out of isRecursive(), avoiding this cross-branch pollution.

Fix cross-branch pollution bug in SchemaConverter recursion detection

---

mcp/mcp-schemas/build.gradle.kts

The mcp-schemas jar is missing the services files entirely. Verified after this change its present in the jar.

Fix service file merging for mcp-schemas

---

smithy-ai-traits/build.gradle.kts
smithy-ai-traits/src/main/java/software/amazon/smithy/ai/PromptUniquenessValidator.java

We want to be able to consume the traits package in JDK 8 packages too. Fixed JDK 8 compatibility in validator tests.
Testing:
`./gradlew clean build` 
```
❯ javap -v 'jar:file:////Volumes/workplace/gateway-live/src/smithy-java/smithy-ai-traits/build/libs/smithy-ai-traits-0.0.2.jar!/software/amazon/smithy/ai/PromptsTrait.class' 'jar:file:////Volumes/workplace/gateway-live/src/smithy-java/smithy-ai-traits/build/libs/smithy-ai-traits-0.0.2.jar!/software/amazon/smithy/ai/PromptTemplateDefinition.class' | grep -B 2 "version:"
Compiled from "PromptsTrait.java"
public final class software.amazon.smithy.ai.PromptsTrait extends software.amazon.smithy.model.traits.AbstractTrait implements software.amazon.smithy.utils.ToSmithyBuilder<software.amazon.smithy.ai.PromptsTrait>
minor version: 0
major …
```

added JDK8 compatibility for smithy-ai-traits

---

codecs/json-codec/build.gradle.kts

After #689 the Maven publishing does not longer generated the javadocs and sources jars for the `json-codec` module. This change is to add those back that are expected to be part of the release.

Fix gradle to generate javadoc and sources jar for publishing

---

.github/workflows/update-gradle-wrapper.yml

Potential fix for [https://github.com/smithy-lang/smithy-java/security/code-scanning/1](https://github.com/smithy-lang/smithy-java/security/code-scanning/1)
To resolve the issue, add a `permissions` block with the minimum required privileges for the workflow. The best way to fix this is to add `permissions: { contents: read }` at the top level of the workflow (just after the `name:` line), which will apply to all jobs in the workflow except those with an override. This change preserves existing functionality while explicitly limiting the GITHUB_TOKEN's access. If the action needs to open pull requests, the minimal required write permission for that purpose (e.g., `pull-requests: write` or `contents: write`) should also be added, but with the information provided, start with `contents: …

Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

mcp/mcp-server/src/main/java/software/amazon/smithy/java/mcp/server/McpServer.java

If the list is of type document the code incorrectly calls `createJsonPrimitiveSchema` which in turns fails with 
```
Schema{id='smithy.example#DocumentList$member', type=document} is not a primitive type
```

Properly support lists of Document's

---

aws/integrations/aws-lambda-endpoint/src/main/java/software/amazon/smithy/java/aws/integrations/lambda/LambdaEndpoint.java
aws/server/aws-server-restjson/src/main/java/software/amazon/smithy/java/aws/server/restjson/AwsRestJson1Protocol.java
http/http-api/src/main/java/software/amazon/smithy/java/http/api/ModifiableHttpHeaders.java
http/http-api/src/main/java/software/amazon/smithy/java/http/api/SimpleModifiableHttpHeaders.java
http/http-api/src/main/java/software/amazon/smithy/java/http/api/SimpleUnmodifiableHttpHeaders.java
server/server-core/src/main/java/software/amazon/smithy/java/server/core/CorsHeaders.java
server/server-core/src/test/java/software/amazon/smithy/java/server/core/TestStructs.java
server/server-netty/src/main/java/software/amazon/smithy/java/server/netty/NettyHttpHeaders.java
server/server-rpcv2-cbor/src/main/java/software/amazon/smithy/java/server/rpcv2/RpcV2CborProtocol.java

The documentation for `putHeader` was previously incorrect: the methods retained old values instead of overwriting them. I renamed them to `addHeader` to be more clear and added a `setHeader` method that behaves the way `putHeader` was originally documented.

Add ModifiableHttpHeaders method to overwrite HTTP header values

---

.github/workflows/update-gradle-wrapper.yml

After taking in GH's automated security fix in #860 , the update gradle wrapper action has been failing because of lack of permissions to create a branch and PRs (https://github.com/smithy-lang/smithy-java/actions/runs/17917802797). This fixes that. 
Also add `workflow_dispatch` trigger so this can be run on demand from the Actions page.

Fix permissions of update-gradle-wrapper and add workflow_dispatch
